language: c

os:
    - linux
    - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get -qq update;
        sudo apt-get -y install libssl-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install openssl;
        brew link openssl --force;
    fi

install:
    - wget "https://github.com/alfredh/pytools/raw/master/ccheck.py"

script: 
    - make EXTRA_CFLAGS=-Werror
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python2 ccheck.py ; fi
